import React, { useState, useEffect } from 'react';
import { fetchDailySummary } from '../utils/api';
import { DailySummary } from '../types';
import { Sparkles, Calendar, TrendingDown, TrendingUp, AlertTriangle, ArrowRight, CheckCircle2 } from 'lucide-react';

interface SummariesProps {
  selectedDate: string;
}

export default function Summaries({ selectedDate }: SummariesProps) {
  const [summary, setSummary] = useState<DailySummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadSummary = async (date: string) => {
    setLoading(true);
    try {
      const data = await fetchDailySummary(date);
      setSummary(data);
      setError(null);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Failed to fetch AI daily summary');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSummary(selectedDate);
  }, [selectedDate]);

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-brand-dark tracking-tight">AI Daily Summary</h1>
          <p className="text-brand-gray-500 mt-1">Get instant business insights and collection suggestions generated by AI.</p>
        </div>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center h-80 space-y-4 bg-brand-card rounded-card border border-brand-gray-200 shadow-soft">
          <div className="relative">
            <div className="w-12 h-12 border-4 border-brand-green border-t-transparent rounded-full animate-spin"></div>
            <Sparkles size={18} className="absolute inset-0 m-auto text-brand-green animate-pulse" />
          </div>
          <p className="text-brand-gray-500 font-semibold text-sm">Gemini AI is analyzing your transactions...</p>
        </div>
      ) : error || !summary ? (
        <div className="bg-brand-card border border-brand-gray-200 rounded-card p-8 text-center text-brand-danger shadow-soft">
          <AlertTriangle className="mx-auto mb-3" size={32} />
          <h3 className="font-bold text-lg">Analysis Unavailable</h3>
          <p className="text-sm text-brand-gray-500 mt-1">{error || 'No records found for this date.'}</p>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Key Figures Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {/* Credit Given */}
            <div className="bg-brand-card p-5 rounded-card border border-brand-gray-200 shadow-soft flex items-center justify-between">
              <div>
                <p className="text-xs font-bold text-brand-gray-500 uppercase tracking-wider">Credit Given</p>
                <h4 className="text-xl font-extrabold text-brand-danger mt-1">₹{summary.credit_given.toLocaleString('en-IN')}</h4>
              </div>
              <div className="p-2 bg-red-50 text-brand-danger rounded-lg">
                <TrendingUp size={18} />
              </div>
            </div>

            {/* Collections */}
            <div className="bg-brand-card p-5 rounded-card border border-brand-gray-200 shadow-soft flex items-center justify-between">
              <div>
                <p className="text-xs font-bold text-brand-gray-500 uppercase tracking-wider">Collections</p>
                <h4 className="text-xl font-extrabold text-brand-success mt-1">₹{summary.collections.toLocaleString('en-IN')}</h4>
              </div>
              <div className="p-2 bg-emerald-50 text-brand-success rounded-lg">
                <TrendingDown size={18} />
              </div>
            </div>

            {/* Net Change */}
            <div className="bg-brand-card p-5 rounded-card border border-brand-gray-200 shadow-soft flex items-center justify-between">
              <div>
                <p className="text-xs font-bold text-brand-gray-500 uppercase tracking-wider">Net Outstanding Change</p>
                <h4 className={`text-xl font-extrabold mt-1 ${summary.net_change >= 0 ? 'text-brand-danger' : 'text-brand-success'}`}>
                  ₹{Math.abs(summary.net_change).toLocaleString('en-IN')}
                  <span className="text-xs font-semibold block text-brand-gray-400 font-sans mt-0.5">
                    {summary.net_change >= 0 ? 'Increase in debt' : 'Decrease in debt'}
                  </span>
                </h4>
              </div>
              <div className={`p-2 rounded-lg ${summary.net_change >= 0 ? 'bg-red-50 text-brand-danger' : 'bg-emerald-50 text-brand-success'}`}>
                {summary.net_change >= 0 ? <TrendingUp size={18} /> : <TrendingDown size={18} />}
              </div>
            </div>
          </div>

          {/* AI Narrative Box */}
          <div className="bg-brand-card border-2 border-brand-green/20 rounded-card p-8 shadow-soft relative overflow-hidden">
            {/* Glowing Gradient Background Layer */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-green-500/5 rounded-full filter blur-3xl pointer-events-none"></div>

            <div className="flex items-center gap-3 border-b border-brand-gray-150 pb-5 mb-5 relative">
              <div className="p-2.5 bg-green-50 text-brand-green rounded-xl border border-green-100 shadow-sm animate-pulse">
                <Sparkles size={20} />
              </div>
              <div>
                <h3 className="font-bold text-lg text-brand-dark">AI Store Analysis</h3>
                <p className="text-xs text-brand-gray-400">Powered by Gemini AI Engine</p>
              </div>
            </div>

            {/* Narrative Content */}
            <div className="prose max-w-none text-brand-gray-800 leading-relaxed space-y-4">
              {summary.summary_text.split('\n').map((line, idx) => {
                const trimmed = line.trim();
                if (!trimmed) return null;
                
                // Formats titles
                if (trimmed.startsWith('#') || trimmed.endsWith(':') && trimmed.length < 50) {
                  return (
                    <h4 key={idx} className="text-brand-dark font-extrabold text-base tracking-tight mt-6 mb-2 flex items-center gap-2">
                      {trimmed.replace(/[#:]/g, '')}
                    </h4>
                  );
                }
                
                // Formats action suggestions
                if (trimmed.toLowerCase().includes('suggested action') || trimmed.toLowerCase().includes('call')) {
                  return (
                    <div key={idx} className="p-4 bg-emerald-50 border border-green-200 rounded-2xl flex gap-3 text-sm text-brand-green font-semibold items-start my-4">
                      <CheckCircle2 size={20} className="shrink-0 mt-0.5" />
                      <div>{trimmed}</div>
                    </div>
                  );
                }

                // Formats bullet points
                if (trimmed.startsWith('-') || trimmed.startsWith('*')) {
                  return (
                    <div key={idx} className="flex gap-2.5 items-start pl-2 text-sm">
                      <span className="text-brand-green mt-1.5 shrink-0">•</span>
                      <span>{trimmed.substring(1).trim()}</span>
                    </div>
                  );
                }

                // Paragraph lines
                return (
                  <p key={idx} className="text-sm font-medium leading-relaxed text-brand-gray-600">
                    {trimmed}
                  </p>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
